### ISSUE TITLE
Вычитание токенов из общего токена

### ISSUE THREAD

**Issue by archeryfox** [pomponchik/cantok#28]
Чтобы токен можно было гонять много раз в виде целого объекта, если нужно несколько условий подряд соблюдать, не перебирать их, а если в ходе пайплайна нам уже не нужно один из токенов, можно было бы удалить ненужный + очистить память от ненужных токенов

**Comment by pomponchik** [comment]
Ответ не поступает уже несколько месяцев, так что пока закрою этот issue. Если вдруг еще актуально - его можно переоткрыть.
