### ISSUE TITLE
Какое основное достоинство cantok по сравнению с Event из stdlib для реализации идеи "cancellation token"?

### ISSUE THREAD

**Issue by zed** [pomponchik/cantok#29]
Допустим я хочу добавить cantok зависимость в набор инструментов, используемых командой. Какие основные аргументы можно озвучить в поддержку токенов из cantok по сравнению реализацией шаблона "cancellation token", используя {asyncio,threading,multiprocessing}.Event (is_set, wait, set методы)? (looking for elevator pitch)

**Comment by pomponchik** [comment]
Привет!

`cantok` не может заменить ивенты из `multiprocessing`. Все, что связано с взаимодействием между процессами - не сюда. Дальше буду говорить только про ивенты из `asyncio` и `threading`.

1. Токены из `cantok` умеют отменяться автоматически, например [по таймауту](https://cantok.readthedocs.io/en/latest/types_of_tokens/TimeoutToken/) или [по произвольному условию](https://cantok.readthedocs.io/en/latest/types_of_tokens/ConditionToken/). Использующему их коду при этом не нужно знать причину, по которой отменен токен, то есть токен полностью инкапсулирует эти причины внутри себя и тем самым упрощает пользовательский код.

2. Токены отмены из `cantok` можно произвольно комбинировать, получая на выходе довольно сложные условия выхода, выраженные очень в простой и визуально понятной форме. К примеру, токены можно [суммировать](https://cantok.readthedocs.io/en/latest/what_are_tokens/summation/).

3. Токены из `cantok` универсальны, они могут быть использованы как в многопоточном, так и в async-коде. Они не заставляют вас выбирать, к какому из лагерей - sync или async - вы хотите отнести свой код.
