### ISSUE TITLE
wait() method could distinguish between awaitable and not-awaitable with inspect.isawaitable()

### ISSUE THREAD

**Issue by kbaikov** [pomponchik/cantok#33]
Perhaps i missing some deeper meaning/use-case but couldn't you just do something like this: 

```python
async def await_me_maybe(callback):
    result = callback()
    if inspect.isawaitable(result):
        return await result
    return result
```
instead of the whole class WaitCoroutineWrapper and its usage?

**Comment by pomponchik** [comment]
Hi!

Method `.wait()` is able to detect the context in which it was called. If it was called as a regular function, the asynchronous version of the `.wait()` will be launched (that is, if you use it in an async context, you block the event loop - you need to remember to type `await` in this case). If you use the `await` keyword before calling, an asynchronous version of the method will be used, which does not block the event loop. Note that in both cases you are calling the same method, but its behavior changes radically depending on whether you have used the `await` keyword.

Read more about this behavior in the [documentation](https://cantok.readthedocs.io/en/latest/what_are_tokens/waiting/).

What you are suggesting would not help to implement this mechanics. "Under the hood" it is implemented on the basis of link counting.
